[project]
name = "streamtoolkit_omkar"
version = "0.1.0"
description = "Modular Streamlit + Secrets Manager Toolkit"
authors = [{name = "Omkar Bhosle"}]
dependencies = ["boto3", "streamlit", "click"]

[project.scripts]
streamtoolkit = "streamtoolkit_omkar.secrets.secrets_cli:cli"
