[project]
name = "streamtoolkit_omkar"
version = "0.1.0"
description = "Reusable modular toolkit for AI-native Streamlit + FastAPI projects"
authors = [{ name = "Omkar Abhay Sawant Bhosle" }]
dependencies = [
    "streamlit",
    "fastapi",
    "openai",
    "boto3",
    "python-dotenv",
    "requests",
    "uvicorn",
    "pyjwt"
]
